name: ElytraParkour
version: 1.1
api-version: 1.15
main: me.jet315.elytraparkour.Core
softdepend: [Multiverse,Multiworld,Multiverse-Core]
commands:
  elytraparkour:
    description: The base command for the ElytraParkour plugin
    aliases: [ep,elytra]